# Generated by Django 3.2.9 on 2022-01-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_alter_entry_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
